### ISSUE TITLE
Problem with UTF-8 strings in variables

### ISSUE THREAD

**Issue by lexusnexus** [interchange/interchange#118]
Perl v5.24.1, Debian GNU/Linux 9.12 (stretch)
Interchange V5.11.0-devel-335-b6d4180a7
I use utf8 encoding for my catalog.

I set variable with Czech word in catalog.cfg:
`Variable mytest manželka`

Then I insert this variable into the Html page:
`[var mytest]`

Output on the page is mangled like this:
> manÅ¾elka

It looks like text converted from utf8 to ASCII somewhere.
I spend 2 days trying to find the bug, but without success (my Perl and Interchange knowledge is weak).
Please help me to fix this error.

**Comment by jonjensen** [comment]
@lexusnexus Thank you for the bug report and simple explanation to reproduce the problem!

Because Interchange is configured to use UTF-8 encoding in the interchange.cfg or catalog.cfg files, it's a little tricky to have data in those files themselves be encoded in UTF-8, and none of us have done that before.

But it was fairly straightforward to get it working. Please see my pull request and give it a try if you can: https://github.com/interchange/interchange/pull/120

If that works for you and others don't object, we'll merge that soon.

**Comment by lexusnexus** [comment]
@jonjensen 
For some reason, this patch is not working for me. I've got the same mangled result.

I solved this for myself by hardcoding decode_utf8 into Config.pm:

``` perl
@@ -30,6 +30,9 @@ require Exporter;

 @EXPORT_OK     = qw( get_catalog_default get_global_default parse_time parse_database);

+require Encode;
+import Encode qw(decode_utf8);
+
 use strict;
 no warnings qw(uninitialized numeric);
 use vars qw(
@@ -5344,7 +5347,7 @@ sub parse_variable {

        ($name, $param) = split /\s+/, $value, 2;
        chomp $param;
-       $c->{$name} = $param;
+       $c->{$name} = decode_utf8($param);
        return $c;
 }
```

**Comment by machack666** [comment]
Hi Alex,

Where were you defining the `Variable MV_UTF8`?  I.e., in your interchange.cfg or catalog.cfg, and after any of the text which needed to be decoded?

Best,

David

--
David Christensen
Senior Software and Database Engineer
End Point Corporation
david@endpoint.com
785-727-1171

**Comment by lexusnexus** [comment]
Thank you, John and David.
This patch works perfectly now. 
It was an error on my side. I haven't defined MV_UTF8 in interchange.cfg (only in catalog.cfg).  Good eye, David :)
