### ISSUE TITLE
RT Ticket #119: Vend::Email module

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#58]
Created: Mon Sep 17 08:13:04 2007
Owner: Stefan Hornburg
Requestors: Kevin Walsh

---

This module doesn't appear to in use; It's just been sitting there
collecting dust for the last four months or so. Has it been abandoned
or are there plans to finish it and hook it up?

This ticket has been raised to see that it either gets completed, or
deleted, prior to the upcoming 5.6.0 stable release.

**Comment by jonjensen** [comment]
@racke Nothing ever happened with this, and Vend::Email has never been integrated into Interchange, so I'm going to remove this module. If you have the integration work all done and can commit it in the next few days, please do! But otherwise, this should just go away as a core module. It can always come back later if someone finishes the work.

**Comment by racke** [comment]
Yes, please go ahead. On one of my sites I'm using Email::Sender :nerd_face: .

**Comment by jonjensen** [comment]
@racke Ok, thanks. Done in commit a1d4d3f01918eb.
