### ISSUE TITLE
Don't use Crypt::Random in UserDB.pm

### ISSUE THREAD

**Issue by jdigory** [interchange/interchange#96]
> On top of that Crypt::Random is hard to install and isn't really not the module of choice otherwise (ask @SysPete about using /dev/random...).

It is also reported as hard to install, although it's part of Bundle::Interchange.

**Comment by jonjensen** [comment]
Who has reported it as hard to install? Where? Details please. I've installed it quite a few places on different Perl versions and OS version and never had a single problem.

**Comment by SysPete** [comment]
The issue is the dep on PARI which I know from experience if not always
available as a simple package. Forcing a user to go and find PARI
sources and compile them because Crypt::Random needs it for accessing
/dev/random and then *not* even using /dev/random in Interchange
suggests that something simpler must be possible.

Personally I switched to Authen::Passphrase a long time ago since it
handles almost any crypt encoding you care to throw at it.

**Comment by jonjensen** [comment]
What Linux server distro does not have a PARI package? I too built it from source long, long ago, and agree that it was a pain. But I think it's been nearly 10 years since that was necessary on RHEL, Debian, or Ubuntu.

Anyway, if you or someone else wants to step up with a compatible patch that uses lighter-weight dependencies, I'm sure everyone would be happy enough to see that. But otherwise, I think we should just close this as a non-problem from a practical point of view. More open issues is not helpful if nobody plans to work on them and they're not actually causing any trouble.

**Comment by jdigory** [comment]
Closing, not a problem issue.
